### ISSUE TITLE
 ControlTransfer with value 8 failed -1

### ISSUE THREAD

**Issue by DiegoGuo** [anotherlab/UsbSerialForAndroid#47]
System.IO.IOException: ControlTransfer with value 8 failed: -1
   at Hoho.Android.UsbSerial.Driver.ProlificSerialDriver.ProlificSerialPort.OutControlTransfer(Int32 requestType, Int32 request, Int32 value, Int32 index, Byte[] data) in D:\log\UsbSerialForAndroid-main\UsbSerialForAndroid\driver\ProlificSerialDriver.cs:line 171
   at Hoho.Android.UsbSerial.Driver.ProlificSerialDriver.ProlificSerialPort.VendorOut(Int32 value, Int32 index, Byte[] data) in D:\log\UsbSerialForAndroid-main\UsbSerialForAndroid\driver\ProlificSerialDriver.cs:line 184
   at Hoho.Android.UsbSerial.Driver.ProlificSerialDriver.ProlificSerialPort.PurgeHwBuffers(Boolean purgeReadBuffers, Boolean purgeWriteBuffers) in D:\log\UsbSerialForAndroid-main\UsbSerialForAndroid\driver\ProlificSerialDriver.cs:line 653
   at Hoho.Android.UsbSerial.Driver.ProlificSerialDriver.ProlificSerialPort.ResetDevice() in D:\log\UsbSerialForAndroid-main\UsbSerialForAndroid\driver\ProlificSerialDriver.cs:line 189
   at Hoho.Android.UsbSerial.Driver.ProlificSerialDriver.ProlificSerialPort.Open(UsbDeviceConnection connection) in D:\log\UsbSerialForAndroid-main\UsbSerialForAndroid\driver\ProlificSerialDriver.cs:line 394
   at Hoho.Android.UsbSerial.Extensions.SerialInputOutputManager.Open(UsbManager usbManager, Int32 bufferSize) in D:\log\UsbSerialForAndroid-main\UsbSerialForAndroid\Extensions\SerialInputOutputManager.cs:line 72

**Comment by anotherlab** [comment]
Please do not post stack traces without any other information.  There is no way to determine what the problem is.

Please see [CONTRIBUTING.md](https://github.com/anotherlab/UsbSerialForAndroid/blob/main/CONTRIBUTING.md) for information on how to report an issue for this library.
